check in publish workflow that correct package exists

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -108,18 +108,32 @@ jobs:
       - name: Install sdist
         run: |
           uv pip install dist/*.tar.gz
-      - name: Check that package JSON file exists
+      - name: Check that Metainfo package JSON file exists and matches definitions version
         run: |
           SITE_PACKAGES=$(python -c "import site; print(site.getsitepackages()[0])")
-          FILE_COUNT=$(find "$SITE_PACKAGES/pynxtools/nomad" -name 'nxs_metainfo_package_*.json' | wc -l)
-          if [ "$FILE_COUNT" -eq 0 ]; then
-            echo "ERROR: nxs_metainfo_package_*.json not found in installed package."
-            exit 1
-          else
-            echo "Found $FILE_COUNT JSON file(s) in package:"
-            find "$SITE_PACKAGES/pynxtools/nomad" -name 'nxs_metainfo_package_*.json'
+
+          # expected filename from definitions module
+          EXPECTED=$(python -c "from pynxtools import get_nexus_version; print(f'nxs_metainfo_package_{get_nexus_version()}.json')")
+
+          # find the JSON file
+          FOUND_FILE=$(find "$SITE_PACKAGES/pynxtools/nomad" -name 'nxs_metainfo_package_*.json' -print -quit)
+
+          if [ -z "$FOUND_FILE" ]; then
+              echo "ERROR: nxs_metainfo_package_*.json not found in installed package."
+              exit 1
           fi
 
+          FOUND_BASENAME=$(basename "$FOUND_FILE")
+
+          echo "Found NeXus schema package JSON file: $FOUND_BASENAME"
+          echo "Expected filename: $EXPECTED"
+
+          if [ "$FOUND_BASENAME" = "$EXPECTED" ]; then
+              echo "✅ Installed NeXus schema package JSON file matches expected definition version."
+          else
+              echo "ERROR: Expected '$EXPECTED', but found '$FOUND_BASENAME'."
+              exit 1
+          fi
   deploy:
     name: Upload to PyPI
     needs: [build, test-install]
